### 1. Obtener todas las materias
GET http://localhost:3000/materias

### 2. Crear una nueva materia
POST http://localhost:3000/materias
Content-Type: application/json

{
  "nombre": "Programación IV"
}

### 3. Obtener todas las calificaciones
GET http://localhost:3000/calificaciones

### 4. Crear una nueva calificación
POST http://localhost:3000/calificaciones
Content-Type: application/json

{
  "alumno": "Adrian Martinez",
  "materia_id": 1,
  "nota1": 9,
  "nota2": 8,
  "nota3": 10
}

### 5. Obtener una calificación por ID
GET http://localhost:3000/calificaciones/1

### 6. Actualizar una calificación
PUT http://localhost:3000/calificaciones/1
Content-Type: application/json

{
  "alumno": "Adrian Martinez Actualizado",
  "nota1": 10
}

### 7. Eliminar una calificación
DELETE http://localhost:3000/calificaciones/1