CREATE DATABASE IF NOT EXISTS db_rectangulos;
USE db_rectangulos;

CREATE TABLE IF NOT EXISTS rectangulos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lado1 DECIMAL(10, 2) NOT NULL,
    lado2 DECIMAL(10, 2) NOT NULL,
    perimetro DECIMAL(10, 2) NOT NULL,
    superficie DECIMAL(10, 2) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);